# References
# https://paulfioravanti.com/blog/2018/10/29/build-a-ci-cd-pipeline-for-your-jekyll-site/
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
- 2.6.3
bundler_args: --without development
before_install:
- gem update --system
- gem install bundler
branches:
  only:
  - update
notifications:
  email: false
script:
- JEKYLL_ENV=production bundle exec jekyll build
deploy:
- provider: pages
  name: Travis Deployment Bot
  skip_cleanup: true
  local_dir: _site
  target_branch: master
  keep_history: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: update
