encoding: utf-8
title: Chris Timperley
email: ctimperley@cmu.edu
baseurl: ""
url: "http://www.christimperley.co.uk"
twitter_username: ChrisTimps
github_username:  ChrisTimperley

# Build settings
markdown: kramdown

plugins: ['jekyll/scholar']

scholar:
  style: bib.csl
  locale: en

  sort_by: year, month
  order: descending
  group_order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib

  bibliography_list_tag: div
  bibliography_item_tag: span

  bibliography_list_attributes:
    reversed: reversed

  replace_strings: true
  join_strings: true

  bibtex_skip_fields:
    - code
    - data
    - tool
    - results

  #repository: materials

  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details

  query: "@*"
