# Site settings
title: Chris Timperley
email: ct584@york.ac.uk
description: >
  Short description of self. Add LinkedIn and Google Scholar.
baseurl: ""
url: "http://christimperley.co.uk"
twitter_username: ChrisTimps
github_username:  ChrisTimperley

# Build settings
markdown: kramdown
